
// Função :calculo de quadrados
// Autor :pedro henrique vicente de carvalho
// Data : 13/04/2021
// Seção de Declarações 
Algoritmo "DESAFIO 01"

VAR
HORAS,MIN:INTEIRO
CONV,TOTAL:REAL

Inicio
ESCREVAL("DIGITE A QUANTIDADE DE HORAS: ")
LEIA(HORAS)
ESCREVAL("DIGITE A QUANTIDADE MINUTOS: ")
LEIA(MIN)

CONV <- MIN/60
TOTAL <- HORAS + CONV

ESCREVAL("TOTAL CONVERTIDO EM HORAS: ",TOTAL)



Fimalgoritmo
