algoritmo "soma das peças"
// Função :peça
// Autor :pedro henrique vicente de carvalho
// Data : 13/04/2021
// Seção de Declarações 

var
valor,quantidade, vt: real

inicio
//entrada

escreva("Qual o valor da peças: ")
leia (valor)
escreval ("Qual a quantidade de peças: ")
leia (quantidade)


//processamento

vt <- quantidade *valor

//saida
escreval("O valor total ?:", vt)

Fimalgoritmo
