algoritmo "imparpar"
// Função :solicitar um valor e informar se ele é par ou impar
// Autor : pedro henrique vicente de carvalho
// Data : 11/05/2021
// Seção de Declarações 
var

num : inteiro
par,impar :logico

inicio
//entrada
escreval ("digite um valor ")
leia(num)


se ((num mod 2)=0) entao
escreval(num,"-esse é um numero par")


senao
escreval(num,"-esse é um numero impar")
fimse

fimalgoritmo
