algoritmo "area_triangulo"

// Função :calcular a area do triangulo
// Autor :pedro carvalho
// Data : 02/03/2021

var

area,base,alt: real

inicio

//entrada de dados
escreval("digite a base do triangulo retangulo")
leia (base)

escreval("digite a altura do triangulo retangulo")
leia (alt)

//processamento
area<- (base*alt)/2

//saida

escreval("a area do triangulo retangulo e:",area,"m2")


fimalgoritmo
