algoritmo "AREA_DO_LOSANGO"

// este algorismo calcula a area do losango
// Autor :pedro carvalho
// Data : 02/03/2021

var
//declaracao de dados

diagonalmaior,diagonalmenor,area:real

inicio
//entrada de dados

escreval ("digite a diagonal maior do losango")
leia (diagonalmaior)

escreval ("digite a diagonal menor do losango")
leia (diagonalmenor)

//processamento
area <- (diagonalmaior+diagonalmenor)

// saida

escreval ("a area do losango e :", area)
fimalgoritmo
