algoritmo "3/15"
// Função : informar os numeros impares
// Autor : pedro henrique vicente de carvalho
// Data : 17/08/2021
// Seção de Declarações 
Var
cont :inteiro

Inicio
escreval("Abaixo temos apenas NUMEROS IMPARES de 101 até o 200")
     para cont de 101 ate 200 passo 2 faca
       escreval("n°= ", cont)
     fimpara
escreval(" espero que tenha feito o desejado.")

Fimalgoritmo
