algoritmo "6/15"
// Função :Este programa irá solicitar 10 Números inteiros e depois fará a soma deles
// Autor :pedro henrique vicente de carvalho
// Data : 17/08/2021
// Seção de Declarações 
var
x,n,soma:inteiro

inicio
 escreval ("Digite 10 numeros iteiros ")
  para n<-1 ate 10 faca
  escreval("Digite um numero= ")
 leia(x)
soma<-soma+x
fimpara
escreval("Resultado=",soma)


escreval(" ISSO É TUDO PESSOAL!!! ")
Fimalgoritmo
